### ISSUE TITLE
Integrate svZeroDSolver into SimVascular

### ISSUE THREAD

**Issue by mrp089** [SimVascular/svZeroDSolver-Archived#23]
Include svZeroDSolver as a git submodule in the SimVascular repository and run it from the GUI

**Comment by ktbolt** [comment]
I've reorganized the `svZeroDSolver.py` file and added a `run_from_c(*args, **kwargs)` function that can now be called from C++. This seems to work.

I needed to add an `__intit__.py` file to enable using the svZeroDSolver package in SV Python/site-packages, also changed some imports to be relative. These changes now prevent calling `svZeroDSolver.py` directly from the git repo because it is not setup as a package there. 

I will reorganize the code into a Python package (see https://github.com/SimVascular/svZeroDSolver/issues/30).
