### ISSUE TITLE
Incorrect equations in BloodVessel element

### ISSUE THREAD

**Issue by JonathanPham** [SimVascular/svZeroDSolver-Archived#51]
There is a small bug in the `BloodVessel` element in `blocks.py`. The second equation does not account for time derivative of the resistance, R, which may be nonlinear if a non-zero `stenosis_coefficient` is provided. 

I will fix this issue by splitting the second equation into two separate equations. This will circumvent the need to compute a time derivative for R, which may be a complicated process.

**Comment by mrp089** [comment]
Looks good @JonathanPham! Thank you for digging into this.

I see that the test cases still pass without requiring any modifications. Is that because our tolerances don't detect the difference in solution? Or is it because our tests are not sensitive to this change? In any case, I think we should modify our test cases so they would have detected this change in results.

**Comment by JonathanPham** [comment]
Just added a test case to reflect the changes!

**Comment by mrp089** [comment]
Awesome work @JonathanPham :anatomical_heart:

That's the way to do it: simple example testing one thing, analytical solution, extremely well documented (what does it test, where do numerical values come from)

**Comment by JonathanPham** [comment]
I agree! Thanks for the initial advice, @mrp089.
